# Generated by Django 4.0.4 on 2022-05-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary')], default=None, max_length=1, null=True, verbose_name='جنسیت'),
        ),
    ]
