# Generated by Django 4.0.4 on 2022-05-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_profile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
