# Generated by Django 4.0.4 on 2022-05-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
