# Generated by Django 4.0.4 on 2022-05-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_profile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(default='http://....com', verbose_name='آدرس وب سایت'),
        ),
    ]
