# Generated by Django 4.0.4 on 2022-05-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default='Unknown.jpg', upload_to='products/', verbose_name='تصویر'),
        ),
    ]
