# Generated by Django 4.0.4 on 2022-05-22 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_profile_website'),
        ('product', '0006_cartitem_remove_cart_active_remove_cart_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
