# Generated by Django 4.0.4 on 2022-05-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='Unknown.jpg', upload_to='media/products', verbose_name='تصویر'),
        ),
    ]
