# Generated by Django 4.0.4 on 2022-05-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_order_alter_product_auther_name_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='good',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
