# Generated by Django 4.0.4 on 2022-05-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_cartitem_cart_remove_cartitem_good_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
